plugins {
    id "com.gradleup.shadow"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

sourceSets.main {
    java.srcDir("../../fabric/src/main/java")
    java.exclude("link/e4steam/fabric/E4steamClientFabric.java")
    java.exclude("link/e4steam/fabric/E4steamFabric.java")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "unstubbedJar")) { transitive false }

    shadowCommon(libs.kaleido.config) { transitive = false }
    shadowCommon("com.code-disaster.steamworks4j:steamworks4j:${rootProject.steamworks4j_version}") {
        transitive = false
    }
    shadowCommon("com.code-disaster.steamworks4j:steamworks4j-server:${rootProject.steamworks4j_version}") {
        transitive = false
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    relocate "folk.sisby.kaleido", "link.e4steam.internal.kaleido"

    exclude("architectury.common.json")
    exclude("steam_api.dll")
    exclude("steamworks4j.dll")
    exclude("steamworks4j-server.dll")
    exclude("steamworks4j-encryptedappticket.dll")
    exclude("steamworks4j-encryptedappticket64.dll")
    exclude("libsteamworks4j-encryptedappticket.so")
    exclude("libsteamworks4j-encryptedappticket.dylib")
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "mc1.17-1.18.2"
}

sourcesJar {
    archiveClassifier = "sources-mc1.17-1.18.2"
    def commonSources = project(":common").unstubbedSourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
