plugins {
    id "java-library"
}

version = rootProject.api_version
base.archivesName = "e4steam-example-addon"

tasks.withType(JavaCompile).configureEach {
    options.release = 8
    options.compilerArgs += ["-Xlint:all", "-Xlint:-options", "-Werror"]
}

dependencies {
    implementation project(":api")
    testImplementation project(":api-testkit")
    testImplementation platform(libs.junit.bom)
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

check.dependsOn(test)
