modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0"

[[mods]]
modId="e4steam"
version="${version}"
displayName="e4steam"
authors="Kamilchik"
description='''Play Minecraft with friends through Steam. Retro build for Minecraft 1.16.5.'''

[[dependencies.e4steam]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="CLIENT"

[[dependencies.e4steam]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="CLIENT"
